# Generated by Django 2.0.3 on 2020-01-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('special', models.BooleanField()),
                ('pepperoni', models.BooleanField()),
                ('cheese', models.BooleanField()),
                ('peppers', models.BooleanField()),
                ('onions', models.BooleanField()),
            ],
        ),
    ]
