# Generated by Django 3.0.2 on 2020-01-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200115_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingNumber', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=5)),
                ('size', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
