# Generated by Django 3.0.2 on 2020-01-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Anchovies',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Artichoke',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Barbecue_Chicken',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Black_Olives',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Buffalo_Chicken',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Canadian_Bacon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Garlic',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Green_Peppers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Ham',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Hamburger',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Sausage',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Spinach',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Tomato_Basil',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Zucchini',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='order',
            name='onions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pepperoni',
        ),
        migrations.RemoveField(
            model_name='order',
            name='peppers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='topping1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='topping2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='topping3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
