# Generated by Django 3.0.2 on 2020-01-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200120_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentlyLoggedInUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, null=True)),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
