# Generated by Django 3.0.2 on 2020-02-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200131_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlyloggedinusers',
            name='username',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
