# Generated by Django 2.0.3 on 2020-02-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_users_staffstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlyloggedinusers',
            name='order',
        ),
    ]
