# Generated by Django 3.0.2 on 2020-01-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200115_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default=0.0, max_length=5),
            preserve_default=False,
        ),
    ]
