# Generated by Django 3.0.2 on 2020-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_column='username_id', max_length=64, primary_key=True, serialize=False),
        ),
    ]
