# Generated by Django 3.0.2 on 2020-02-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200207_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='pizzaprices',
            name='size',
            field=models.CharField(max_length=7),
        ),
    ]
