# Generated by Django 2.0.3 on 2020-02-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='staffStatus',
            field=models.NullBooleanField(),
        ),
    ]
