# Generated by Django 2.0.3 on 2020-03-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_currentlyloggedinusers_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
                ('itemsNeededCodes', models.TextField(null=True)),
                ('itemsNeededQuantities', models.TextField(null=True)),
            ],
        ),
    ]
